# Generated by Django 4.2 on 2023-04-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Main_Navigation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("ordering", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Main Navigation",
                "verbose_name_plural": "Main Navigations",
                "ordering": ["ordering"],
            },
        ),
    ]
