# Generated by Django 4.2 on 2023-04-25 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("userProfile", "0003_vendorprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pasal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pasal_reference_name", models.CharField(max_length=200)),
                ("pasal_address", models.CharField(max_length=100)),
                ("pasal_uid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("password", models.CharField(max_length=30)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="VendorProfile",),
    ]
