# Generated by Django 4.2 on 2023-04-25 07:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("userProfile", "0004_pasal_delete_vendorprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pasal",
            name="pasal_uid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
